package com.johann.style

fun getWeatherIcon(data: String) = when (data) {
    "clearsky_day" -> R.drawable.clearsky_day
    "clearsky_night" -> R.drawable.clearsky_night
    "clearsky_polartwilight" -> R.drawable.clearsky_polartwilight
    "cloudy" -> R.drawable.cloudy
    "fair_day" -> R.drawable.fair_day
    "fair_night" -> R.drawable.fair_night
    "fair_polartwilight" -> R.drawable.fair_polartwilight
    "fog" -> R.drawable.fog
    "heavyrain" -> R.drawable.heavyrain
    "heavyrainandthunder" -> R.drawable.heavyrainandthunder
    "heavyrainshowers_day" -> R.drawable.heavyrainshowers_day
    "heavyrainshowers_night" -> R.drawable.heavyrainshowers_night
    "heavyrainshowers_polartwilight" -> R.drawable.heavyrainshowers_polartwilight
    "heavyrainshowersandthunder_day" -> R.drawable.heavyrainshowersandthunder_day
    "heavyrainshowersandthunder_night" -> R.drawable.heavyrainshowersandthunder_night
    "heavyrainshowersandthunder_polartwilight" -> R.drawable.heavyrainshowersandthunder_polartwilight
    "heavysleet" -> R.drawable.heavysleet
    "heavysleetandthunder" -> R.drawable.heavysleetandthunder
    "heavysleetshowers_day" -> R.drawable.heavysleetshowers_day
    "heavysleetshowers_night" -> R.drawable.heavysleetshowers_night
    "heavysleetshowers_polartwilight" -> R.drawable.heavysleetshowers_polartwilight
    "heavysnow" -> R.drawable.heavysnow
    "heavysnowandthunder" -> R.drawable.heavysnowandthunder
    "heavysnowshowers_day" -> R.drawable.heavysnowshowers_day
    "heavysnowshowers_night" -> R.drawable.heavysnowshowers_night
    "heavysnowshowers_polartwilight" -> R.drawable.heavysnowshowers_polartwilight
    "lightrain" -> R.drawable.lightrain
    "lightrainandthunder" -> R.drawable.lightrainandthunder
    "lightrainshowers_day" -> R.drawable.lightrainshowers_day
    "lightrainshowers_night" -> R.drawable.lightrainshowers_night
    "lightrainshowers_polartwilight" -> R.drawable.lightrainshowers_polartwilight
    "lightsleet" -> R.drawable.lightsleet
    "lightsleetshowers_day" -> R.drawable.lightsleetshowers_day
    "lightsleetshowers_night" -> R.drawable.lightsleetshowers_night
    "lightsleetshowers_polartwilight" -> R.drawable.lightsleetshowers_polartwilight
    "lightsnow" -> R.drawable.lightsnow
    "lightsnowandthunder" -> R.drawable.lightsnowandthunder
    "lightsnowshowers_day" -> R.drawable.lightsnowshowers_day
    "lightsnowshowers_night" -> R.drawable.lightsnowshowers_night
    "lightsnowshowers_polartwilight" -> R.drawable.lightsnowshowers_polartwilight
    "partlycloudy_day" -> R.drawable.partlycloudy_day
    "partlycloudy_night" -> R.drawable.partlycloudy_night
    "partlycloudy_polartwilight" -> R.drawable.partlycloudy_polartwilight
    "rain" -> R.drawable.rain
    "rainandthunder" -> R.drawable.rainandthunder
    "rainshowers_day" -> R.drawable.rainshowers_day
    "rainshowers_night" -> R.drawable.rainshowers_night
    "rainshowers_polartwilight" -> R.drawable.rainshowers_polartwilight
    "rainshowersandthunder_day" -> R.drawable.rainshowersandthunder_day
    "rainshowersandthunder_night" -> R.drawable.rainshowersandthunder_night
    "rainshowersandthunder_polartwilight" -> R.drawable.rainshowersandthunder_polartwilight
    "sleet" -> R.drawable.sleet
    "sleetandthunder" -> R.drawable.sleetandthunder
    "sleetshowers_day" -> R.drawable.sleetshowers_day
    "sleetshowers_night" -> R.drawable.sleetshowers_night
    "sleetshowers_polartwilight" -> R.drawable.sleetshowers_polartwilight
    "snow" -> R.drawable.snow
    "snowandthunder" -> R.drawable.snowandthunder
    "snowshowers_day" -> R.drawable.snowshowers_day
    "snowshowers_night" -> R.drawable.snowshowers_night
    "snowshowers_polartwilight" -> R.drawable.snowshowers_polartwilight
    else -> android.R.drawable.ic_delete
}